### ISSUE TITLE
Zen does not build with Zig 0.6

### ISSUE THREAD

**Issue by cinemast** [AndreaOrru/zen#43]
Here is the build log:

```
./build.zig:23:27: error: array literal requires address-of operator to coerce to slice type '[][]const u8'
    const common_params = [][]const u8 {
                          ^
./build.zig:24:9: note: referenced here
        "qemu-system-i386",
        ^
./build.zig:48:11: error: no member named 'setOutputPath' in struct 'std.build.LibExeObjStep'
    kernel.setOutputPath("zen");
          ^
./build.zig:66:11: error: no member named 'setOutputPath' in struct 'std.build.LibExeObjStep'
    server.setOutputPath("servers/" ++ name ++ "/" ++ name);
          ^
./build.zig:11:33: note: called from here
    const terminal = buildServer(b, "terminal");
                                ^
./build.zig:6:32: note: called from here
pub fn build(b: *Builder) void {
                               ^
./build.zig:66:11: error: no member named 'setOutputPath' in struct 'std.build.LibExeObjStep'
    server.setOutputPath("servers/" ++ name ++ "/" ++ name);
          ^
./build.zig:12:33: note: called from here
    const keyboard = buildServer(b, "keyboard");
                                ^
./build.zig:6:32: note: called from here
pub fn build(b: *Builder) void {
                               ^
./build.zig:66:11: error: no member named 'setOutputPath' in struct 'std.build.LibExeObjStep'
    server.setOutputPath("servers/" ++ name ++ "/" ++ name);
          ^
./build.zig:14:33: note: called from here
    const shell    = buildServer(b, "shell");
                                ^
./build.zig:6:32: note: called from here
pub fn build(b: *Builder) void {
```

**Comment by AndreaOrru** [comment]
Hi, thanks for pointing it out. I think it hasn't been building for a few months now.

I plan to revamp the code base at some point in the next few weeks, so stay tuned ;)

**Comment by sskras** [comment]
What's up with the revamping?

**Comment by AndreaOrru** [comment]
I'll be rebooting this using a modern version of Zig. Stay tuned.
